require:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.3

# Offense count: 1
# Configuration parameters: CountComments, ExcludedMethods.
Metrics/BlockLength:
  Max: 31

# Offense count: 1
# Configuration parameters: ExpectMatchingDefinition, Regex, IgnoreExecutableScripts, AllowedAcronyms.
Naming/FileName:
  Exclude:
    - 'lib/rubocop-sequel.rb'
