version: 2.1

steps: &steps
  steps:
    - checkout
    - run: bundle install
    - run: bundle exec rubocop --parallel
    - run: bundle exec rspec

jobs:
  ruby-2-3:
    docker:
      - image: circleci/ruby:2.3
    <<: *steps

  ruby-2-4:
    docker:
      - image: circleci/ruby:2.4
    <<: *steps

  ruby-2-5:
    docker:
      - image: circleci/ruby:2.5
    <<: *steps

workflows:
  build:
    jobs:
      - ruby-2-3
      - ruby-2-4
      - ruby-2-5
